crab fixed
ram1123/nanoAOD_vvVBS pull request #29
Opened 2024-01-12 10:19 UTC by YujiLee301

Hi Ram,

I have taken efforts and made everything works in crabjobs based on our master branch.

Please change your storage location of T2 site in crab_cfg.py and run command:
crab submit --config=crab_cfg.py

Looking for your review, thanks in advance.

Best,
Yuji

2024-01-14 15:18 UTC, ram1123 requested changes
Delete directory `crab_projects_sendPythonFolderFalse`. This is created when we submit the job.

2024-01-14 15:18 UTC, ram1123 commented on FrameworkJobReport.xml
Delete this file.

2024-01-14 15:18 UTC, ram1123 commented on crab_script.py
Do we need this file? I don't see importing this module or mention in the README. Please check

2024-01-16 05:07 UTC, YujiLee301 commented on FrameworkJobReport.xml
I tested without this file, and the submission can not be successful.

2024-01-16 05:09 UTC, YujiLee301 commented on crab_script.py
No, we do not need it. Actually post_proc.py is what makes sense. So I deleted this module.

2024-01-19 13:50 UTC, ram1123 commented on FrameworkJobReport.xml
hmmm, strange. This should be autogenerated.

Can you try to find out how crab job depends on this file?

2024-01-19 14:05 UTC, ram1123 commented
Hi @YujiLee301 ,

It looks like you do not stat from the "HZZ_Analysis" branch for the crab job update.

Remember that our master branch is "HZZ_Analysis". So, for any update start from the "HZZ_Analysis" branch as a base branch then rename it (say `crabjobs`).

As you didn't start from the "HZZ_Analysis" branch there is a merge conflict as I updated the base branch of the job. Please check and fix it.

2024-01-23 10:05 UTC, ram1123 commented
This update moved to PR #31

2024-01-23 10:05 UTC, closed without merging